# 퍼셉트론

## 퍼셉트론 구조
![image](https://user-images.githubusercontent.com/28241676/146882607-3f7bd4ab-9ab2-46a6-bb6e-f5d08d490932.png)
![image](https://user-images.githubusercontent.com/28241676/146882697-392e505f-09a6-44ca-b68a-d90874501556.png)
![image](https://user-images.githubusercontent.com/28241676/146882685-5cee5ae4-3b64-408b-a38b-937eecc9cf5d.png)

In [2]:
import numpy as np

In [3]:
X = np.array([[1, 0, 0],
              [1, 1, 0],
              [1, 0, 1],
              [1, 1, 1]])
Y = np.array([-1, 1, 1, 1])
W = np.array([-0.5, 1.0, 1.0])

act_fn = lambda x : np.array([1 if o >= 0 else -1 for o in x])

In [4]:
output = act_fn(np.dot(X, W.T))
output

array([-1,  1,  1,  1])

In [6]:
output == Y

array([ True,  True,  True,  True])

## 퍼셉트론 학습

![image](https://user-images.githubusercontent.com/28241676/146883746-89317b9b-8674-4cf8-9e0f-f087d49f5e0a.png)

# 다층 퍼셉트론

![image](https://user-images.githubusercontent.com/28241676/146884052-da83d74e-e397-421e-ba77-ab793f902a8a.png)
![image](https://user-images.githubusercontent.com/28241676/146884207-e536a79d-fdb3-41d2-a956-c9ac2f2fb36e.png)

In [28]:
X = np.array([[1, 0, 0],
              [1, 1, 0],
              [1, 0, 1],
              [1, 1, 1]])
Y = np.array([-1, 1, 1, -1])
W1 = np.array([[-0.5, 1.0, 1.0],
               [1.5, -1., -1.0]])
W2 = np.array([-1., 1.0, 1.0])

act_fn1 = lambda x : np.array([[1. if o >= 0. else -1 for o in h]for h in x])
act_fn2 = lambda x : np.array([1 if o >= 0 else -1 for o in x])

In [29]:
hidden_z = act_fn1(np.dot(X, W1.T))
hidden_z = np.append(np.array([[1],[1],[1],[1]]), hidden_z, axis=1)
hidden_z

array([[ 1., -1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1., -1.]])

In [30]:
output = act_fn2(np.dot(hidden_z, W2.T))
output

array([-1,  1,  1, -1])

In [31]:
output == Y

array([ True,  True,  True,  True])